name: Rust Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Cache Rust dependencies
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-
  

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
          	sudo\
          	lsb-release\
          	cmake\
          	wget\
          	curl\

      - name: Perform Build
        run: |
          cargo build --release
